server:
  port: ${PORT:8080}

spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

logging:
  level:
    org.springdoc: DEBUG
    org.springframework: INFO

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: ${JWT_EXPIRES_MS:3600000}

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
  s3:
    endpoint: ${S3_ENDPOINT}
    region: ${S3_REGION}
    accessKey: ${S3_ACCESS_KEY}
    secretKey: ${S3_SECRET_KEY}
    bucket: ${S3_BUCKET}
    publicBaseUrl: ${S3_PUBLIC_BASE}
  jwt:
    secret: ${security.jwt.secret:${JWT_SECRET}}
    expires-ms: ${security.jwt.expiration-ms:${JWT_EXPIRES_MS:3600000}}

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings
  endpoint:
    health:
      show-details: always

